<h1> Plasmando en código el funcionamiento de las redes neuronales Artificiales - Parte 1</h1>

### Para que podamos entrar en contexto sobre nuestro tema principal, primero les quiero hacer hacer una pequeña explicación de cómo funciona una neurona simple en el ser humano, cuyo compratmiento es el que queremos imitar en una máquina.


En este módulo aprenderemos los conecptos básicos y las noticiones aritméticas y estadistas de cómo funciona una red neuronal artificial así como entener con un código simple su funcionamiento y luego utilizar librerías conocidas como TensorFlow 2.0

## 1. La Neurona Humana
![NeuronUrl](https://media.giphy.com/media/5h9EHCvA0OR2/giphy.gif "neuron")

En el gif podemos apreciar las redes nueronales y lo increíble de esto es poder entender cómo imitar el compartamiento de una neurona humana con la de una máquina ¿Y por qué hacemos esto? es simple, nuestro cerebro humano es una máquina compleja capaz de resolver operaciones -que para una computadora parece muy compleja- con muchísima facilidad. Imaginate poder recrear, la información que recibimos con nuestros ojos desde una cámara, la percepción de colores, procesarlos y obtener información para que realice una tarea que nos ayude. Imitar el funcionamiento del cerebro humano nos ayuda a extender nuestras posibilidades como seres humanos.

Entonces nuestro desafío principal está en como recrear una neurona. Para ello, vamos a ver analizar su funcionamiento.

![RamonUrl](https://supercurioso.com/wp-content/uploads/2014/12/ramonycajalelartistadelaneurona.jpg "ramon")

En el año 1899 Santiago Ramón y Cajal (imagen derecha) lo que hizo fue teñir las neuronas y observarlas bajo el microscopio y trazó la imagen de lo que el creía se trataba de una neurona individual (imagen izquierda).

Años más tarde, con la llegada de nuevas tecnologías permitieron una mejor observación y como mostraremos en la imagen más abajo, una estructura real y gráfica de la neurona es muy parecida a la imagen de Santiago.

![EstructuraUrl](https://respuestas.tips/wp-content/uploads/2013/10/partes-de-una-neurona.jpg "estructura")

En realidad, es mucho más compleja en cuanto a todas las partes que la componen, pero quiero que nos enfoquemos en tres partes importantes de la neurona, las dendritas, el axón y el núcleo.

Lo que tenemos que entender aquí es que las neuronas por sí solas no sirven, deben convivir con otras para su correcto funcionamiento para lograr cosas increíbles que ya conocemos.

¿Cómo trabajan juntas?

Bueno, las dendritas, reciben la información, pasa por el núcleo y el axón se encarga de llevar esta información a otra neurona, básicamente transmiten impulsos eléctricos desde el axón a las dendritas de otra neurona y este proceso es al que se le conoce como sinapsis y para que se hagan una idea nuestra cerebro en edad adulta cuenta con 86 mil millones de neuronas en promedio.

Ahora, vamos a empezar a estudiar como logramos plasmar la neurona humana en una máquina.

![EstructuraUrl](https://miro.medium.com/max/642/1*ifwiDM2fRKze9VBG2p6_Bg.png "estructura")

Entre las décadas del 1950 y 1960 el psicológo y científico estadounidense, inspirado en el trabajo de otros científicos, crea algo que hoy conocemos como perceptrón (imagen de arriba). Que es la únidad básica de inferencia o una neurona artificial.

Ahora imaginemos a las fechas como dendritas y las X como información que le pasa otra neurona, entonces las flechas serían las sinapsis. En este caso la señal que le pasamos, vendría a ser una valor de entrada y a partir de estos valores generan un valor de salida. A las entradas les llamamos variables independientes porque pueden ser cualquier valor por separado y a la salida como variable dependiente porque es un resultado que depende de las entradas. Y a las la sinapsis que vemos ahora los llamaremos pesos "w" como la imagen de abajo:

![EstructuraUrl](https://miro.medium.com/max/642/1*ifwiDM2fRKze9VBG2p6_Bg.png "estructura")

Esta sinapsis que ahora le llamaremos pesos o comúnmente representado por "w" son fundamentales para el correcto funcionamiento de nuestro perceptrón porque estos valores de pesos se utilizan para que pueda aprender qué valor de entrada a la neuora es importante y que no. De hecho lo único que ajustamos cuando entrenamos una red neuronal es ajustar los valores de los pesos constantemente, pero ¿por qué?

El entrenamiento tiene dos pasos

    Primer paso:
    El entrenamiento lo que hace es una suma total del valor de entrada multiplicado por los pesos es decir: x1.w1 + x2.w2 + xn*wn. A esto se le conoce como suma ponderada y podemos representarlo con la siguiente ecuación:
    
   $$\sum\limits_{i=0}^{m} {x_i*w_i}$$  
    
    Segundo paso:
    A nuestra suma ponderada le aplicamos una función de activación delta (no se preocupen veremos a continuación que es esta función). Quedando así finalmente 
    
   $$\delta(\sum\limits_{i=0}^{m} {x_i*w_i})$$ 


## 2. Función de activación

La función de activación es la que me permite definir el comportamiento de mi neurona y de cada capa, esta función decide que valor pasa o se queda. Hablaremos brevemente de 4 de ellas.

- Threshold Function o escalón unitario
![EstructuraUrl](https://miro.medium.com/max/960/0*etGrZj_m0spvgN9n.png "estructura")
Esta es la función más simple, como verán cuando recibe valore negativos (menores a 0) la función está en cero y cuando recibe valores positivos (mayores a 0) la función pasa a ser 1, es decir nuestro valor de salida siempre va a ser 1 y 0 nada más. Ahora que comprendemos como es una función de activación básica vamos a uno un poco más compleja.


- Función Sigmoide
![EstructuraUrl](https://miro.medium.com/max/744/1*zSDNMn4z_hmYing0wDCSoQ.png "sigmoide")
Como vemos esta función es un poco más suave, pasa por todos los valores entre 0 y 1, es muy últil cuando queremos calcular probabilidades en nuestra salida.


- Función Rectificadora
![EstructuraUrl](https://miro.medium.com/max/736/1*RthaUGkni6YCtwlAKsadsg.png "recti")
Es una de las funciones más utilizadas en Machine Learning, esto lo que hace simplemente es entregarnos los valores cuando seán mayores a cero, es decir, valor positivo. Para cada valor positivo un valor de la curva.


- Tangente Hiperbólica
![EstructuraUrl](https://miro.medium.com/max/772/1*sYnLa9djWZ7BozqUV5lNmw.png "hiper")
Esta función es muy similar a la Sigmoide pero va desde -1 a 1 los valores.

Quisiera que puedas tener en mente esto ya que todavía no entraremos a profundidad pero si los veremos más adelante.

## 3. ¿Cómo funcionan las Redes Neuronales Artificiales en un caso real?

Vamos a imaginar que hacemos una clasificación, vamos a usar un dataset, en este caso y para ejemplo el de Titanic, donde nos trae una lista de pasajeros y si sobrevivieron o no. A continuación vamos a representar nuestro perceptrón con las variables y se ve así:

![EstructuraUrl](https://miro.medium.com/max/1084/1*_pD95maLHcEL8Hc39EMJGA.png "ti")

Para este caso es súper fácil calcular ya que el resultado es simplemente la suma ponderada con la función de activación. Pero que pasa si añado más capacas de a nuestro modelo, es decir, todas las entradas iran conectadas a la capa siguiente como vemos en la siguiente imagen, eso significa que podríamos predecir más valores, aunque no piensen que si tenemos más capa mejora el resultado.

![EstructuraUrl](https://miro.medium.com/max/1084/1*YjtSTddpDPCscJSXcQblBg.png "j")

Mientras más capas tengas más nivel de abstracción va a tener nuestra red. Recuerden que básicamente cada una recibe un valor de peso distinto por lo que puede o no recibir esa entrada x en algunos perceptrones, de esta manera, cada uno realiza una función difrente, aunque no siempre sea así.

## 4. ¿Cómo aprenden las redes neuronales?

En programación hay muchas maneras de llegar a una solución, por ejemplo, podríamos programar todos los casos y respuestas para una solución posible. Cuando esta tarea lleva variables que no siempre se van a comportar como el algoritmo espera, por ejemplo. Queremos crear algo que reconzca un perro en cualquier fotos in importar la raza. Suena sencillo, clasifico las imagenes, digo que son perros, y listo. Pero esta tarea se complica ya que existen n razas de perros, pueden salir en n tipo de ambientes en la fotografía y con diferentes tipos de poses, para esto, es mucho más complicado tener un código que lo resuleva o programar cada caso, para ello se crean las redes neuronales artificiales, claro, para nosotros es natural saber que hay un perro en la foto pero para la máquina no.

La ventaja de las redes neuronales es que puede "entender" los datos que le damos de entrada y hacer una función para cualquier entrada que le presentemos, y como buen ejemplo hemos dado la imagen del perro.

Veamos de nuevo la red neuronal anterior...
![EstructuraUrl](https://miro.medium.com/max/1084/1*YjtSTddpDPCscJSXcQblBg.png "j")
Lo que vamos a hacer es calcular el valor de la salida "y" (si murió o no) en base a nuestro dato de entrada "x" (variables que vemos arriba). Además de esto le vamos a pasar a Y valores reales de que si murió o no. ¿Pero entonces de que me sirve la predicción en "y" si le paso los valores reales?. Es simple, al final de cada paso por la neurona, la máquina lo que va a a hacer es comparar el valor de salida de la predicción con el valor real, esto se hace a través de la función de pérdida y podemos verlo en la siguiente ecuación:
$$L = {1 \over 2}(\Upsilon - y)^2$$
Aquí Upsilon (la y medio rara que se ve ahí jajaja) es nuestro valor predecido y la y normal es nuestro valor real. Esta es la más común entre las funciones de pérdida y esta se llama "Mean Squered Error" o la medidad de los errores al cuadrado. Esta función lo que nos dice es cuánto es el error que va a tener nuestra red y lo que tenemos que hacer es minimizarla.
Esta función va para atrás y corrije los pesos para ir minizando los pesos "w".

## 5. ¿Cómo es que minimizo mi función de perdida?

Bueno para poder minizar la función de perdida podríamos utilizar algo que se llama el descenso de gradiente (aclaro que este texto no muestra la unica forma pero si trato de simplificar lo máximo posible para adentrarnos en este complejo mundo).
Lo que hace esta función es tratar de encontrar los valores de los pesos de modo a que el error se ajuste con la pendiente de la recta dentro del conjunto de valores (puntos azules) que serían las entradas como se aprecia en el siguiente gif:

![EstructuraUrl](https://miro.medium.com/proxy/1*KQVi812_aERFRolz_5G3rA.gif)

Pero que pasa si nuestra función no representa una parabola y tiene varios mínimos como se ve a continuación

![EstructuraUrl](https://miro.medium.com/max/1400/0*XKMTnu8MwD2wdso6.png)

Si nuestro algoritmo solamente encuentra un mínimo local no encontrará un mínimo global que es el que neceitamos para que se ajusten los valores de los pesos.

Entonces con el descendo de gradiente lo que nuestra función hace en cada paso es
- Paso el dato 1
- Paso el dato 2
- Paso el dato 3
- Ajusto los pesos

Para solucionar el problema anterior donde tenemos varios mínimos posibles se utiliza otro algoritmo que hace algo que se llama descenso de gradiente estocástico y hace lo siguiente
- Paso el dato 1
- Ajusto los pesos
- Paso el dato 2
- Ajusto los pesos
- Paso el dato 3
- Ajusto los pesos

Entonces cada vez que pase por el dato va a justar los pesos y se acercará más al mínimo global ya que se mueve constantemente ante cada paso de datos.

## 5. Backpropagation

Todo lo que vimos hasta ahora es lo que se llama comunmente Forward Propagation, donde el valor de entrada, pasa por toda la red, pasa por la función de activación, se calcula la función de pérdida, luego de este proceso la pérdida se debe "propagar hacia atrás" ajustando los valores de los pesos, esto es lo que hace el backpropagation, ir para atrás y ajustar los valores de los pesos a la vez en simultáneo, es un algoritmo con unas matemáticas muy avanzadas e interesantes que los puedes mirar por tu cuenta si quieres :)

## 6. Manos a la obra

Ahora lo que haremos es aplicar una pequeña red neuronal sin utilizar ninguna librería especial excepto la de numpy. Numpy es una libería de python que nos permite realizar operaciones matemáticas complejas con una fácil implementación del código.

---
Como primer paso lo que haremos es instalar esta libería en caso de que nuestra PC no lo tenga, si estás usando algún otro editor puedes instalarlo desde tu terminal quitando el signo de exclamación que tiene en frente.

Recuerden que para ejecutar un bloque de código como el que ven abajo solo deben ubicar el cursos sobre el bloque y presionar SHIFT+ENTER y así sucesivamente.



In [11]:
!pip3 install numpy

---
Importamos la librería de numpy


In [12]:
import numpy as np

---
Lo que hacemos en este punto crear una función que calcule nuestra función de activación, que sería una variante de la función sigmoide.
Tengamos en cuenta que creamos esta función para usarlo en sus dos formas, si queremos como sus derivadas o no.


In [15]:
def nonlin(x, deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

---
Lo que hacemos aquí abajo es crear dos matrices, una matriz "x" que ya sabemos que es la entrada "y" que son los valores reales de la salida osea los resultados reales.

Recuerden que esos datos que presentamos en la entrada son valores cualquiera, solo representan una entrada que queremos que nos brinde una salida predictiva.



In [22]:
x = np.array([[0,0,1],
      [0,1,1],
      [1,0,1],
      [1,1,1]])
y = np.array([[0],
      [1],
      [1],
      [0]])

---
Aquí lo que haremos es crear valores de pesos de manera randomica, que la computadora me los genere por que es lo que voy a ir corrigiendo con el algoritmo. Los imprimo para que los veamos.
Supongamos que vamos a tener dos capas

In [87]:
np.random.seed(1)

w1 = 2*np.random.random((3,4))-1
w2 = 2*np.random.random((4,1))-1

print(w1)
print(w2)

[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]


---
Bueno aquí empieza lo divertido 😊
Supogamos que L1 y L2 son las capas.
Lo que vamos a hacer primero es el #Forward Propagation, en este paso primero guardamos en "L0" nuestros valores de "x" y luego hacemos un producto punto con los valores de los pesos (suma ponderarda) y lo pasamos por la función de activación como se puestra en L1, estos valores se multiplican con los valores anteriores y los pesos de la capa 2.

Luego en #Cálculo de erro lo que hacemos es calcular nuestro error de los valores reales con nuestras predicciones para hallar el valor de pérdida. Esto hacemos restando el valor de real con el valor que se predijo.

¿Recuerdan que hablamos sobre el algoritmo de descenso de gradiente?. Bueno eso se calcula multiplicando el error actual por la derivada de la función que creamos con las predicciones actuales (por eso decidimos tener una opción de derivada más arriba) Recuerde la derivada es la recta tangente en un punto a la función.

#Backpropagation.. Una vez que tengamos el descenso de gradiente (la pendiente) multimplicamos por la transpuesta de los pesos de la capa siguiente y de este modo propagaremos el error hacia atrás.

Y finalmente #ajustamos el valor de los pesos con la transpuesta de las capas por sus respectivas optimizaciones o direcciones hacia donde actualizar los pesos y esto suman a nuestros pesos actuales modificando los dos a la vez.

In [90]:
for j in range(6000):
    #Forward Propagation
    L0 = x
    L1 = nonlin(np.dot(L0,w1))
    L2 = nonlin(np.dot(L1,w2)) 
    
    #Cálculo de error
    L2_error = y - L2       
    
    #Calculamos el descenso de gradiente
    L2_delta = L2_error*nonlin(L2,deriv=True)
    
    #Backpropagation
    L1_error = L2_delta.dot(w2.T)
    L1_delta = L1_error * nonlin(L1,deriv=True)
    
    #ajustamos el valor de los pesos
    w2 += L1.T.dot(L2_delta)
    w1 += L0.T.dot(L1_delta)

Ahora analicemos los resultados, vemos como aquí nuestro valores "y" que son los reales vs los valores que la máquina predijo que serían. ¿Muy loco no?

In [110]:
print("Valores reales\n")
print(y)
print("\n")
print("Valores de las predicciones\n")
print(L2)

Valores reales

[[0]
 [1]
 [1]
 [0]]


Valores de las predicciones

[[0.00631758]
 [0.99192018]
 [0.99291766]
 [0.0094266 ]]
